spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.dbname}
    username: ${db.username}
    password: ${db.password}

  config:
    import: "classpath:API-KEY.properties"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    # sql log ???
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.hibernate.sql: debug
    org.mybatis: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.developer.user.query.dto

