spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:0000/0000
    username: ${db.username}
    password: ${db.password}

  jpa:
    # ??? ?? (JPA?? ??)
    hibernate:
      ddl-auto: create-drop


    # sql log ???
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.hibernate.sql: debug

