server:
  port: 0

spring:
  application:
    name: with-the-developer-post-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.dbname}
    username: ${db.username}
    password: ${db.password}
  config:
    import: "classpath:API-KEY.properties"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    # sql log ???
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.hibernate.sql: debug
    org.mybatis: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.developer.block.query.dto, com.developer.msg.query.dto, com.developer.block.query.dto

cloud:
  aws:
    s3:
      bucket: ${s3.bucket} # Amazon S3 버킷 이름
    stack.auto: false
    region.static: ap-southeast-2
    credentials:
      accessKey: ${im.access} # IAM 액세스 키
      secretKey: ${im.secret} # IAM 시크릿 키