server:
  port: 8000

spring:
  application:
    name: with-the-developer-gateway-server
  cloud:
    gateway:
      routes:
        - id: with-the-developer-user-service
          uri: lb://WITH-THE-DEVELOPER-USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka