server:
  port: 8000

spring:
  config:
    import:
      - classpath:bootstrap.yml
  application:
    name: with-the-developer-gateway-server
  cloud:
    gateway:
      routes:
        - id: with-the-developer-user-service
          uri: lb://WITH-THE-DEVELOPER-USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: with-the-developer-post-service
          uri: lb://WITH-THE-DEVELOPER-POST-SERVICE
          predicates:
            - Path=/post-service/**
          filters:
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
jwt:
  secret: 6ko5/kvgL64BhiLQY74jo31u77ihmQX+LjwpvJISgjo5uObMZeuxUPX5EMHV8/AfPgZ3IyyqzJGApMw4EkW8TQ==

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka